dist: bionic

language: python

python:
  - 3.7
  - 3.8

before_install:
  - pip install cython
  - sudo apt-get -y install pocl-opencl-icd clinfo

install:
  - pip install -e .

before_script:
  - pip install pytest pytest-cov codecov
  - clinfo
  - python .travis/context_info.py

script:
  - pytest -v --cov-config=.coveragerc --cov=./peridynamics

after_success:
  - codecov

jobs:
  include:
    - name: Lint
      before_install:
      install:
      before_script: pip install flake8 flake8-docstrings
      script: flake8
      after_success:
    - name: Build documentation
      before_script: pip install sphinx
      script: sphinx-build -W -b html docs build
      after_success:
